server:
  port: ${APPLICATION_PORT:8083}
spring:
  main.allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      group-id: "spring-kafka-send-reply"
      properties:
        spring.json:
          trusted.packages: "com.tabeldata.message.model, com.tabeldata.message.sendreplyjson.example.model, java.util, java.lang"
