POST {{host}}:8081{{context-path}}/api/kafka/string/no-reply?desc=Selamat anda mendapatkan pulsa sebesar 1jt rupiah
Content-Type: application/json

### seding string request

POST {{host}}:{{port}}{{context-path}}/api/kafka/json/no-reply
Content-Type: application/json

{
  "transactionId": "{{$randomInt}}",
  "stan": "00001",
  "cardNumber": "{{$uuid}}",
  "amount": "100000"
}

### sending json request
