POST {{host}}:8084{{context-path}}/api/kafka/without-transaction/success
Content-Type: application/json

{
  "requestBy": "user001",
  "partNumber": "{{$uuid}}",
  "qty": "{{$randomInt}}"
}

### sending request without transaction manager

POST {{host}}:8084{{context-path}}/api/kafka/proxy-transaction/success
Content-Type: application/json

{
  "requestBy": "user001",
  "partNumber": "{{$uuid}}",
  "qty": "{{$randomInt}}"
}

### sending request with proxy config @Transactional
