server:
  port: ${APPLICATION_PORT:8082}
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      group-id: "spring-kafka-send-reply"
      properties:
        spring.json:
          trusted.packages: "com.tabeldata.message.model, java.util, java.lang"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
